"""Strict relq schema code generation."""

from relq_codegen.config import load_config
from relq_codegen.errors import CodegenError
from relq_codegen.generate import generate_postgres, generate_sqlite, write_module
from relq_codegen.introspection import inspect_postgres, inspect_postgres_enums, inspect_sqlite
from relq_codegen.model import (
    ArrayType,
    Attribute,
    BuiltinType,
    Call,
    CodegenConfig,
    CodegenDialect,
    DirectType,
    GeneratedWrapper,
    Import,
    Name,
    NamedType,
    RejectedType,
    RenderExpression,
    SchemaColumn,
    SchemaEnum,
    SchemaTable,
    SqlType,
    StringLiteral,
    Subscript,
    TypeIdentity,
    TypeMapping,
    Union,
)
from relq_codegen.render import render

__all__ = [
    "ArrayType",
    "Attribute",
    "BuiltinType",
    "Call",
    "CodegenConfig",
    "CodegenDialect",
    "CodegenError",
    "DirectType",
    "GeneratedWrapper",
    "Import",
    "Name",
    "NamedType",
    "RejectedType",
    "RenderExpression",
    "SchemaColumn",
    "SchemaEnum",
    "SchemaTable",
    "SqlType",
    "StringLiteral",
    "Subscript",
    "TypeIdentity",
    "TypeMapping",
    "Union",
    "generate_postgres",
    "generate_sqlite",
    "inspect_postgres",
    "inspect_postgres_enums",
    "inspect_sqlite",
    "load_config",
    "render",
    "write_module",
]
