"""Deterministic Python source renderer for normalized schema metadata."""

from __future__ import annotations

import keyword
import re
from collections.abc import Mapping

from relq_codegen.mapping import relq_decoder, resolve_type, used_wrapper_policies
from relq_codegen.model import (
    Call,
    CodegenConfig,
    Import,
    RenderExpression,
    SchemaColumn,
    SchemaEnum,
    SchemaTable,
    TypeIdentity,
)


def render(
    tables: tuple[SchemaTable, ...],
    *,
    enums: tuple[SchemaEnum, ...] = (),
    config: CodegenConfig | None = None,
) -> str:
    """Render deterministic Python source from already-normalized metadata."""
    imports = {
        Import("collections.abc", ("Iterable",)),
        Import("typing", ("Literal", "NotRequired", "Required", "TypedDict")),
        Import(
            "relq",
            ("Column", "InsertQuery", "Table", "UpdateQuery", "column", "insert_into", "update"),
        ),
    }
    body: list[str] = ['"""Generated by relq-codegen; do not edit manually."""', ""]
    exported: list[str] = []
    enum_names = _enum_names(enums)
    enum_types = {
        database_enum.identity: enum_names[database_enum.identity] for database_enum in enums
    }
    if enums:
        imports.add(Import("enum"))
    for database_enum in enums:
        class_name = enum_names[database_enum.identity]
        exported.append(class_name)
        body.append(f"class {class_name}(enum.StrEnum):")
        used_names: set[str] = set()
        for index, label in enumerate(database_enum.labels):
            member = _enum_member_name(label, index, used_names)
            used_names.add(member)
            body.append(f"    {member} = {label!r}")
        body.append("")

    policies = used_wrapper_policies(tables, config)
    if policies:
        imports.add(Import("typing", ("NewType",)))
    for policy in policies:
        if policy.name in exported:
            raise ValueError(f"generated wrapper name collides with an enum: {policy.name}")
        imports.update(policy.base.annotation.imports())
        exported.append(policy.name)
        body.extend(
            (f"{policy.name} = NewType({policy.name!r}, {policy.base.annotation.render()})", "")
        )

    for table in tables:
        class_name = _class_name(table.name)
        exported.append(class_name)
        body.append(f"class {class_name}(Table):")
        if not table.columns:
            body.append("    pass")
        for field in table.columns:
            resolved = resolve_type(field.sql_type, enum_types, config)
            imports.update(resolved.imports())
            annotation = (
                f"{resolved.annotation.render()} | None"
                if field.nullable
                else resolved.annotation.render()
            )
            attribute = _attribute_name(field.name)
            arguments = [resolved.annotation.render()]
            if attribute != field.name:
                arguments.append(f"name={field.name!r}")
            body.append(
                f"    {attribute}: Column[{annotation}] = column(" + ", ".join(arguments) + ")"
            )
        body.append("")
        instance_name = _attribute_name(table.name)
        insert_payload = f"{class_name}Insert"
        update_payload = f"{class_name}Update"
        insert_function = f"insert_{instance_name}"
        update_function = f"update_{instance_name}"
        exported.extend(
            (
                instance_name,
                insert_payload,
                update_payload,
                insert_function,
                f"{insert_function}_many",
                update_function,
                f"{class_name}Row",
                f"{instance_name}_row_adapter",
            )
        )
        body.extend((f"{instance_name} = {class_name}({table.name!r})", ""))
        _render_payload(
            body, insert_payload, table.columns, kind="insert", enum_types=enum_types, config=config
        )
        body.append("")
        _render_payload(
            body, update_payload, table.columns, kind="update", enum_types=enum_types, config=config
        )
        body.extend(
            (
                "",
                f"def {insert_function}(values: {insert_payload}) -> InsertQuery[tuple[()], Literal[False]]:",
                f"    return insert_into({instance_name}).values(**values)",
                "",
                f"def {insert_function}_many(values: Iterable[{insert_payload}]) -> InsertQuery[tuple[()], Literal[False]]:",
                f"    return insert_into({instance_name}).values_many(values)",
                "",
                f"def {update_function}(values: {update_payload}) -> UpdateQuery[tuple[()], Literal[False], Literal[False]]:",
                f"    return update({instance_name}).values(**values)",
                "",
            )
        )
        imports.update(_render_row_model(body, table, enum_types=enum_types, config=config))
    body.insert(1, "\n".join(item.render() for item in sorted(imports, key=Import.render)))
    body.append("__all__ = [" + ", ".join(repr(name) for name in exported) + "]")
    return "\n".join(body) + "\n"


def _enum_names(enums: tuple[SchemaEnum, ...]) -> Mapping[TypeIdentity, str]:
    counts: dict[str, int] = {}
    for database_enum in enums:
        stem = _class_name(database_enum.identity.name)
        counts[stem] = counts.get(stem, 0) + 1
    return {
        database_enum.identity: (
            _class_name(f"{database_enum.identity.schema}_{database_enum.identity.name}")
            if counts[_class_name(database_enum.identity.name)] > 1
            else _class_name(database_enum.identity.name)
        )
        for database_enum in enums
    }


def _render_payload(
    body: list[str],
    name: str,
    columns: tuple[SchemaColumn, ...],
    *,
    kind: str,
    enum_types: Mapping[TypeIdentity, str],
    config: CodegenConfig | None,
) -> None:
    payload_columns = tuple(column for column in columns if not column.generated)
    if not all(
        column.name.isidentifier() and not keyword.iskeyword(column.name)
        for column in payload_columns
    ):
        fields = ", ".join(
            f"{column.name!r}: {_payload_field_annotation(column, kind, enum_types, config)}"
            for column in payload_columns
        )
        body.append(f"{name} = TypedDict({name!r}, {{{fields}}})")
        return
    body.append(f"class {name}(TypedDict):")
    if not payload_columns:
        body.append("    pass")
        return
    for field in payload_columns:
        body.append(
            f"    {field.name}: {_payload_field_annotation(field, kind, enum_types, config)}"
        )


def _payload_field_annotation(
    field: SchemaColumn,
    kind: str,
    enum_types: Mapping[TypeIdentity, str],
    config: CodegenConfig | None,
) -> str:
    resolved = resolve_type(field.sql_type, enum_types, config)
    annotation = (
        f"{resolved.annotation.render()} | None" if field.nullable else resolved.annotation.render()
    )
    if kind == "insert" and not (
        field.nullable or field.primary_key or field.has_default or field.identity
    ):
        return f"Required[{annotation}]"
    return f"NotRequired[{annotation}]"


def _render_row_model(
    body: list[str],
    table: SchemaTable,
    *,
    enum_types: Mapping[TypeIdentity, str],
    config: CodegenConfig | None,
) -> set[Import]:
    class_name = _class_name(table.name)
    row_name = f"{class_name}Row"
    adapter_name = f"{_attribute_name(table.name)}_row_adapter"
    body.extend(("", "@dataclass(frozen=True, slots=True)", f"class {row_name}:"))
    if not table.columns:
        body.append("    pass")
    decoders: list[RenderExpression | None] = []
    for field in table.columns:
        resolved = resolve_type(field.sql_type, enum_types, config)
        annotation = (
            f"{resolved.annotation.render()} | None"
            if field.nullable
            else resolved.annotation.render()
        )
        body.append(f"    {_attribute_name(field.name)}: {annotation}")
        decoder = resolved.decoder
        decoders.append(
            Call(relq_decoder("nullable"), (decoder,)) if field.nullable and decoder else decoder
        )
    decoder_tuple = (
        "("
        + ", ".join(decoder.render() if decoder is not None else "None" for decoder in decoders)
        + ("," if len(decoders) == 1 else "")
        + ")"
    )
    body.extend(
        (
            "",
            f"{adapter_name} = row_adapter(",
            f"    {row_name},",
            f"    decoders={decoder_tuple},",
            ")",
        )
    )
    imports = {Import("dataclasses", ("dataclass",)), Import("relq", ("row_adapter",))}
    for decoder in decoders:
        if decoder is not None:
            imports.update(decoder.imports())
    return imports


def _class_name(name: str) -> str:
    result = "".join(part.capitalize() for part in re.split(r"[^0-9A-Za-z]+", name) if part)
    if not result or result[0].isdigit():
        return "Table_" + (result or "Generated")
    return result


def _attribute_name(name: str) -> str:
    result = re.sub(r"\W", "_", name)
    if not result or result[0].isdigit():
        result = "column_" + result
    if result in {"class", "def", "from", "import", "pass", "return", "type"}:
        result += "_"
    return result


def _enum_member_name(label: str, index: int, used: set[str]) -> str:
    candidate = re.sub(r"\W", "_", label).upper().strip("_") or f"VALUE_{index + 1}"
    if candidate[0].isdigit():
        candidate = "VALUE_" + candidate
    if keyword.iskeyword(candidate.lower()):
        candidate += "_"
    base = candidate
    suffix = 2
    while candidate in used:
        candidate = f"{base}_{suffix}"
        suffix += 1
    return candidate
