"""Generated by relq-codegen; do not edit manually."""
from collections.abc import Iterable
from dataclasses import dataclass
from relq import AwareDateTime
from relq import Column, InsertQuery, Table, UpdateQuery, column, insert_into, update
from relq import NaiveTime
from relq import aware_datetime_decoder
from relq import bool_decoder
from relq import decimal_decoder
from relq import enum_decoder
from relq import inet_decoder
from relq import int_decoder
from relq import json_decoder
from relq import list_decoder
from relq import naive_time_decoder
from relq import nullable
from relq import row_adapter
from relq import str_decoder
from relq import uuid_decoder
from typing import Literal, NotRequired, Required, TypedDict
import decimal
import enum
import ipaddress
import uuid

class RelqIntegrationState(enum.StrEnum):
    NEW = 'new'
    IN_PROGRESS = 'in-progress'
    DONE = 'done'

class RelqCodegenValues(Table):
    id: Column[int] = column(int)
    tenant: Column[int] = column(int)
    identifier: Column[uuid.UUID | None] = column(uuid.UUID)
    states: Column[list[RelqIntegrationState]] = column(list[RelqIntegrationState])
    price: Column[decimal.Decimal] = column(decimal.Decimal)
    occurred_at: Column[AwareDateTime | None] = column(AwareDateTime)
    due_time: Column[NaiveTime | None] = column(NaiveTime)
    payload: Column[object | None] = column(object)
    origin: Column[ipaddress.IPv4Address | ipaddress.IPv6Address | ipaddress.IPv4Interface | ipaddress.IPv6Interface | None] = column(ipaddress.IPv4Address | ipaddress.IPv6Address | ipaddress.IPv4Interface | ipaddress.IPv6Interface)
    computed: Column[int | None] = column(int)

relq_codegen_values = RelqCodegenValues('relq_codegen_values')

class RelqCodegenValuesInsert(TypedDict):
    id: NotRequired[int]
    tenant: Required[int]
    identifier: NotRequired[uuid.UUID | None]
    states: NotRequired[list[RelqIntegrationState]]
    price: NotRequired[decimal.Decimal]
    occurred_at: NotRequired[AwareDateTime | None]
    due_time: NotRequired[NaiveTime | None]
    payload: NotRequired[object | None]
    origin: NotRequired[ipaddress.IPv4Address | ipaddress.IPv6Address | ipaddress.IPv4Interface | ipaddress.IPv6Interface | None]

class RelqCodegenValuesUpdate(TypedDict):
    id: NotRequired[int]
    tenant: NotRequired[int]
    identifier: NotRequired[uuid.UUID | None]
    states: NotRequired[list[RelqIntegrationState]]
    price: NotRequired[decimal.Decimal]
    occurred_at: NotRequired[AwareDateTime | None]
    due_time: NotRequired[NaiveTime | None]
    payload: NotRequired[object | None]
    origin: NotRequired[ipaddress.IPv4Address | ipaddress.IPv6Address | ipaddress.IPv4Interface | ipaddress.IPv6Interface | None]

def insert_relq_codegen_values(values: RelqCodegenValuesInsert) -> InsertQuery[tuple[()], Literal[False]]:
    return insert_into(relq_codegen_values).values(**values)

def insert_relq_codegen_values_many(values: Iterable[RelqCodegenValuesInsert]) -> InsertQuery[tuple[()], Literal[False]]:
    return insert_into(relq_codegen_values).values_many(values)

def update_relq_codegen_values(values: RelqCodegenValuesUpdate) -> UpdateQuery[tuple[()], Literal[False], Literal[False]]:
    return update(relq_codegen_values).values(**values)


@dataclass(frozen=True, slots=True)
class RelqCodegenValuesRow:
    id: int
    tenant: int
    identifier: uuid.UUID | None
    states: list[RelqIntegrationState]
    price: decimal.Decimal
    occurred_at: AwareDateTime | None
    due_time: NaiveTime | None
    payload: object | None
    origin: ipaddress.IPv4Address | ipaddress.IPv6Address | ipaddress.IPv4Interface | ipaddress.IPv6Interface | None
    computed: int | None

relq_codegen_values_row_adapter = row_adapter(
    RelqCodegenValuesRow,
    decoders=(int_decoder(), int_decoder(), nullable(uuid_decoder()), list_decoder(enum_decoder(RelqIntegrationState)), decimal_decoder(), nullable(aware_datetime_decoder()), nullable(naive_time_decoder()), nullable(json_decoder()), nullable(inet_decoder()), nullable(int_decoder())),
)
class RelqIntegrationArchive(Table):
    id: Column[int] = column(int)
    name: Column[str] = column(str)

relq_integration_archive = RelqIntegrationArchive('relq_integration_archive')

class RelqIntegrationArchiveInsert(TypedDict):
    id: NotRequired[int]
    name: Required[str]

class RelqIntegrationArchiveUpdate(TypedDict):
    id: NotRequired[int]
    name: NotRequired[str]

def insert_relq_integration_archive(values: RelqIntegrationArchiveInsert) -> InsertQuery[tuple[()], Literal[False]]:
    return insert_into(relq_integration_archive).values(**values)

def insert_relq_integration_archive_many(values: Iterable[RelqIntegrationArchiveInsert]) -> InsertQuery[tuple[()], Literal[False]]:
    return insert_into(relq_integration_archive).values_many(values)

def update_relq_integration_archive(values: RelqIntegrationArchiveUpdate) -> UpdateQuery[tuple[()], Literal[False], Literal[False]]:
    return update(relq_integration_archive).values(**values)


@dataclass(frozen=True, slots=True)
class RelqIntegrationArchiveRow:
    id: int
    name: str

relq_integration_archive_row_adapter = row_adapter(
    RelqIntegrationArchiveRow,
    decoders=(int_decoder(), str_decoder()),
)
class RelqIntegrationUsers(Table):
    id: Column[int] = column(int)
    manager_id: Column[int | None] = column(int)
    name: Column[str] = column(str)
    active: Column[bool] = column(bool)
    state: Column[RelqIntegrationState] = column(RelqIntegrationState)
    state_history: Column[list[RelqIntegrationState]] = column(list[RelqIntegrationState])
    name_length: Column[int | None] = column(int)

relq_integration_users = RelqIntegrationUsers('relq_integration_users')

class RelqIntegrationUsersInsert(TypedDict):
    id: NotRequired[int]
    manager_id: NotRequired[int | None]
    name: Required[str]
    active: NotRequired[bool]
    state: NotRequired[RelqIntegrationState]
    state_history: NotRequired[list[RelqIntegrationState]]

class RelqIntegrationUsersUpdate(TypedDict):
    id: NotRequired[int]
    manager_id: NotRequired[int | None]
    name: NotRequired[str]
    active: NotRequired[bool]
    state: NotRequired[RelqIntegrationState]
    state_history: NotRequired[list[RelqIntegrationState]]

def insert_relq_integration_users(values: RelqIntegrationUsersInsert) -> InsertQuery[tuple[()], Literal[False]]:
    return insert_into(relq_integration_users).values(**values)

def insert_relq_integration_users_many(values: Iterable[RelqIntegrationUsersInsert]) -> InsertQuery[tuple[()], Literal[False]]:
    return insert_into(relq_integration_users).values_many(values)

def update_relq_integration_users(values: RelqIntegrationUsersUpdate) -> UpdateQuery[tuple[()], Literal[False], Literal[False]]:
    return update(relq_integration_users).values(**values)


@dataclass(frozen=True, slots=True)
class RelqIntegrationUsersRow:
    id: int
    manager_id: int | None
    name: str
    active: bool
    state: RelqIntegrationState
    state_history: list[RelqIntegrationState]
    name_length: int | None

relq_integration_users_row_adapter = row_adapter(
    RelqIntegrationUsersRow,
    decoders=(int_decoder(), nullable(int_decoder()), str_decoder(), bool_decoder(), enum_decoder(RelqIntegrationState), list_decoder(enum_decoder(RelqIntegrationState)), nullable(int_decoder())),
)
__all__ = ['RelqIntegrationState', 'RelqCodegenValues', 'relq_codegen_values', 'RelqCodegenValuesInsert', 'RelqCodegenValuesUpdate', 'insert_relq_codegen_values', 'insert_relq_codegen_values_many', 'update_relq_codegen_values', 'RelqCodegenValuesRow', 'relq_codegen_values_row_adapter', 'RelqIntegrationArchive', 'relq_integration_archive', 'RelqIntegrationArchiveInsert', 'RelqIntegrationArchiveUpdate', 'insert_relq_integration_archive', 'insert_relq_integration_archive_many', 'update_relq_integration_archive', 'RelqIntegrationArchiveRow', 'relq_integration_archive_row_adapter', 'RelqIntegrationUsers', 'relq_integration_users', 'RelqIntegrationUsersInsert', 'RelqIntegrationUsersUpdate', 'insert_relq_integration_users', 'insert_relq_integration_users_many', 'update_relq_integration_users', 'RelqIntegrationUsersRow', 'relq_integration_users_row_adapter']
