"""Generated by relq-codegen; do not edit manually."""
from collections.abc import Iterable
from dataclasses import dataclass
from relq import Column, InsertQuery, Table, UpdateQuery, column, insert_into, update
from relq import datetime_decoder
from relq import int_decoder
from relq import nullable
from relq import row_adapter
from relq import str_decoder
from typing import Literal, NotRequired, Required, TypedDict
import datetime

class SnapshotUsers(Table):
    id: Column[int] = column(int)
    email: Column[str] = column(str)
    created_at: Column[datetime.datetime | None] = column(datetime.datetime)

snapshot_users = SnapshotUsers('snapshot_users')

class SnapshotUsersInsert(TypedDict):
    id: NotRequired[int]
    email: Required[str]
    created_at: NotRequired[datetime.datetime | None]

class SnapshotUsersUpdate(TypedDict):
    id: NotRequired[int]
    email: NotRequired[str]
    created_at: NotRequired[datetime.datetime | None]

def insert_snapshot_users(values: SnapshotUsersInsert) -> InsertQuery[tuple[()], Literal[False]]:
    return insert_into(snapshot_users).values(**values)

def insert_snapshot_users_many(values: Iterable[SnapshotUsersInsert]) -> InsertQuery[tuple[()], Literal[False]]:
    return insert_into(snapshot_users).values_many(values)

def update_snapshot_users(values: SnapshotUsersUpdate) -> UpdateQuery[tuple[()], Literal[False], Literal[False]]:
    return update(snapshot_users).values(**values)


@dataclass(frozen=True, slots=True)
class SnapshotUsersRow:
    id: int
    email: str
    created_at: datetime.datetime | None

snapshot_users_row_adapter = row_adapter(
    SnapshotUsersRow,
    decoders=(int_decoder(), str_decoder(), nullable(datetime_decoder())),
)
__all__ = ['SnapshotUsers', 'snapshot_users', 'SnapshotUsersInsert', 'SnapshotUsersUpdate', 'insert_snapshot_users', 'insert_snapshot_users_many', 'update_snapshot_users', 'SnapshotUsersRow', 'snapshot_users_row_adapter']
